apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-deployment-pipeline
description: Deployment pipeline for GKE
serialPipeline:
  stages:
  - targetId: gke-deployment-pipeline-target-1	
    profiles:
    - deploy

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: gke-deployment-pipeline-target-1	
description: Development environment
gke:
  cluster: my-cluster
  location: us-east1-c
  namespace: dev