steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-east1-docker.pkg.dev/docker2gcp/gke/ui-app:latest'
    - './UserInterface'
  id: "Build Docker Image for UserInterface"

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-east1-docker.pkg.dev/docker2gcp/gke/ui-app:latest'
  id: "Push Docker Image for UserInterface"

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-east1-docker.pkg.dev/docker2gcp/gke/db-app:latest'
    - './Database'
  id: "Build Docker Image for Database"

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-east1-docker.pkg.dev/docker2gcp/gke/db-app:latest'
  id: "Push Docker Image for Database"

- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      gcloud deploy apply --file deploy/pipeline.yaml --region=us-east1
      gcloud deploy apply --file deploy/dev.yaml --region=us-east1
    #gcloud deploy apply --file deploy/prod.yaml --region=us-east1

      gcloud deploy releases create "db-release-${SHORT_SHA}" \
        --delivery-pipeline=gke-cicd-pipeline \
        --region=us-east1 \
        --from-k8s-manifest=./Database/database-deployment.yaml

options:
  logging: CLOUD_LOGGING_ONLY
