steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'us-east1-docker.pkg.dev/docker2gcp/gke/ui-app:latest'
  - './UserInterface'
  id: "Build Docker Image for UserInterface"

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'us-east1-docker.pkg.dev/docker2gcp/gke/ui-app:latest'
  id: "Push Docker Image for UserInterface"

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'us-east1-docker.pkg.dev/docker2gcp/gke/db-app:latest'
  - './Database'
  id: "Build Docker Image for Database"

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'us-east1-docker.pkg.dev/docker2gcp/gke/db-app:latest'
  id: "Push Docker Image for Database"


# # Step 5: Deploy to GKE
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['apply', '-f', './Database/database-deployment.yaml']
#   id: "Deploy Database to GKE"
# Deploy via Cloud Deploy


# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   args:
#     - 'deploy'
#     - 'releases'
#     - 'create'
#     - 'release-$SHORT_SHA'
#     - '--delivery-pipeline=gke-deployment-pipeline'
#     - '--region=us-east1' # Change to your Cloud Deploy region
#     - '--images=db-app=gcr.io/$PROJECT_ID/db-app:$SHORT_SHA'
#   id: "Trigger Cloud Deploy"

# substitutions:
#   _CLUSTER: "my-cluster"
#   _ZONE: "us-east1-c"
options:
  logging: CLOUD_LOGGING_ONLY