apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
profiles:
  - prod
gke: 
  cluster: projects/docker2gcp/locations/us-east1-c/clusters/my-cluster