apiVersion: v1
kind: Service
metadata:
  name: db-app-service
  namespace: database
spec:
  type: LoadBalancer  # Change from ClusterIP to LoadBalancer
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: db-app
