apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app
  namespace: ui
  labels:
    app: ui-app
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
      - name: ui-app
        image: us-east1-docker.pkg.dev/docker2gcp/gke/ui-app:latest  # Replace with your image from Google Artifact Registry
        ports:
        - containerPort: 5002  # Port your app runs on
        env:
        - name: DB_APP_IP
          value: "35.231.112.222"  # Use the service name of the db-app
        - name: DB_APP_PORT
          value: "5001"  # Port of the db-app service
        - name: GCP_SERVICE_ACCOUNT_FILE
          value: /app/docker2gcp-b80ec434f87f.json
---
apiVersion: v1
kind: Service
metadata:
  name: ui-app-service
  namespace: ui
spec:
  type: LoadBalancer
  ports:
    - port: 5002  # Port exposed by the service
      targetPort: 5002  # Port the container listens on
  selector:
    app: ui-app  # This should match the labels of the deployment
