apiVersion: v1
kind: Service
metadata:
  name: ui-app-service
  namespace: ui
spec:
  type: LoadBalancer
  ports:
    - port: 5002  # Port exposed by the service
      targetPort: 5002  # Port the container listens on
  selector:
    app: ui-app  # This should match the labels of the deployment
